// ⚠️ FICHIER AUTO-GÉNÉRÉ — ne pas modifier manuellement
// Modifie CLIENT.md puis relance : npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: "Jimmy",
    nomDirigeant: "Delannoy",
    nomEntreprise: "JD Maintenance et Plomberie",
    nomLegal: "JD MAINTENANCE ET PLOMBERIE",
    genreDirigeant: "masculin",
    founder: "Jimmy Delannoy",
  },
  contact: {
    telephone: "07 69 94 95 28",
    telephoneHref: "tel:+33769949528",
    telephoneUrgence: "07 69 94 95 28",
    email: "jdmaintenance38118@gmail.com",
    adresse: "15 Route du Greillon",
    ville: "Saint-Baudille-de-la-Tour",
    codePostal: "38118",
    departement: "Isère",
    region: "Auvergne-Rhône-Alpes",
    zoneIntervention: "Saint-Baudille-de-la-Tour et 30km autour",
    zoneKm: "30",
  },
  horaires: {
    semaine: "8h00 - 18h00",
    samedi: "8h00 - 12h00",
    dimanche: "Fermé",
    urgence: "7j/7, 24h/24",
  },
  branding: {
    couleurPrimaireHue: "210",
    couleurAccentHue: "44",
  },
  social: {
    facebook: "",
    instagram: "",
    google: "",
  },
  domaine: "jd-maintenance-plomberie.fr",
  url: "https://www.jd-maintenance-plomberie.fr",
  legal: {
    siret: "991 496 654",
    rge: "",
    assuranceDecennale: "",
  },
  chiffres: {
    anneesExperience: 1,
    nombreInterventions: 200,
    noteGoogle: 5,
    nombreAvis: 0,
    anneeCreation: 2025,
    delaiIntervention: "2h",
    disponibilite: "7j/7",
    tauxSatisfaction: "100",
  },
  geo: {
    latitude: "45.748",
    longitude: "5.349",
  },
  communes: [
    { name: "Saint-Baudille-de-la-Tour", postalCode: "38118" },
    { name: "Hières-sur-Amby", postalCode: "38118" },
    { name: "Crémieu", postalCode: "38460" },
    { name: "Optevoz", postalCode: "38460" },
    { name: "Siccieu-Saint-Julien-et-Carisieu", postalCode: "38460" },
    { name: "La Balme-les-Grottes", postalCode: "38390" },
    { name: "Parmilieu", postalCode: "38390" },
    { name: "Annoisin-Chatelans", postalCode: "38460" },
    { name: "Villemoirieu", postalCode: "38460" },
    { name: "Soleymieu", postalCode: "38460" },
    { name: "Trept", postalCode: "38460" },
    { name: "Dizimieu", postalCode: "38460" },
    { name: "Saint-Hilaire-de-Brens", postalCode: "38460" },
    { name: "Frontonas", postalCode: "38290" },
    { name: "Verna", postalCode: "38150" },
    { name: "Morestel", postalCode: "38510" },
    { name: "Creys-Mépieu", postalCode: "38510" },
    { name: "Arandon-Passins", postalCode: "38510" },
    { name: "Montalieu-Vercieu", postalCode: "38390" },
    { name: "Bourgoin-Jallieu", postalCode: "38300" },
    { name: "La Tour-du-Pin", postalCode: "38110" },
    { name: "L'Isle-d'Abeau", postalCode: "38080" },
    { name: "Villefontaine", postalCode: "38090" },
    { name: "Pont-de-Chéruy", postalCode: "38230" },
    { name: "Tignieu-Jameyzieu", postalCode: "38230" },
    { name: "Charvieu-Chavagneux", postalCode: "38230" },
  ],
  services: [
    { title: "Dépannage urgent", shortDescription: "Intervention rapide pour toutes vos urgences plomberie dans le Nord-Isère.", description: "Fuite d'eau, canalisation bouchée, dégât des eaux, panne de chaudière... Jimmy intervient en urgence 7j/7 dans un rayon de 30 km autour de Saint-Baudille-de-la-Tour. Diagnostic sur place et réparation immédiate dans la majorité des cas.", icon: "Siren", slug: "/depannage-plomberie" },
    { title: "Plomberie générale", shortDescription: "Installation, remplacement et mise aux normes de vos équipements.", description: "Robinetterie, tuyauterie, raccordements, WC, éviers, recherche de fuite... JD Maintenance et Plomberie intervient pour tous vos travaux de plomberie, de l'installation neuve à la mise aux normes de vos installations existantes.", icon: "Wrench", slug: "/plomberie" },
    { title: "Salle de bain", shortDescription: "Rénovation complète, douche italienne, adaptation PMR.", description: "De la conception à la réalisation, Jimmy prend en charge votre projet de rénovation de salle de bain. Douche italienne, remplacement baignoire, accessibilité PMR, meuble vasque... Un interlocuteur unique du début à la fin.", icon: "Bath", slug: "/renovation-salle-de-bain" },
    { title: "Chauffage", shortDescription: "Chaudière, pompe à chaleur, plancher chauffant, entretien annuel.", description: "Installation et remplacement de chaudière gaz condensation, pompe à chaleur air-eau, plancher chauffant, radiateurs. Entretien annuel obligatoire et dépannage de votre système de chauffage.", icon: "Flame", slug: "/chauffage" },
    { title: "Chauffe-eau", shortDescription: "Remplacement, ballon thermodynamique, détartrage.", description: "Remplacement de chauffe-eau électrique ou gaz, installation de ballon thermodynamique pour réduire votre facture énergétique. Détartrage et entretien pour prolonger la durée de vie de votre équipement.", icon: "Droplets", slug: "/chauffe-eau" },
    { title: "Maintenance", shortDescription: "Contrats d'entretien et maintenance préventive de vos installations.", description: "L'entretien régulier de vos installations de plomberie et chauffage est essentiel. JD Maintenance propose des contrats d'entretien incluant la visite annuelle, le dépannage prioritaire et les pièces d'usure.", icon: "ClipboardCheck", slug: "/chauffage#entretien" },
  ],
  testimonials: [
    { name: "Marie L.", rating: 5, text: "Jimmy est intervenu très rapidement pour une fuite sous l'évier. Travail propre et soigné. Je recommande vivement !", date: "2025-11-15", source: "Google" },
    { name: "Pierre D.", rating: 5, text: "Remplacement de notre vieux chauffe-eau par un modèle thermodynamique. Explications claires, installation impeccable. Très professionnel.", date: "2025-12-02", source: "Google" },
    { name: "Sophie M.", rating: 5, text: "Rénovation complète de notre salle de bain à Crémieu. Résultat magnifique, délais respectés. Jimmy est à l'écoute et de bon conseil.", date: "2026-01-10", source: "Google" },
    { name: "Laurent B.", rating: 4, text: "Bon travail pour le débouchage de nos canalisations. Intervention rapide un samedi matin. Tarifs corrects.", date: "2025-10-28", source: "Google" },
    { name: "Isabelle R.", rating: 5, text: "Excellente prestation pour l'installation de notre nouvelle chaudière gaz. Jimmy a pris le temps de nous expliquer le fonctionnement. Très satisfaite.", date: "2026-01-22", source: "Google" },
    { name: "Jean-Marc T.", rating: 5, text: "Intervention d'urgence pour un dégât des eaux. Jimmy est arrivé en moins d'une heure. Problème résolu efficacement. Merci !", date: "2025-11-05", source: "Google" },
    { name: "Catherine V.", rating: 5, text: "Réfection complète de la plomberie de notre maison ancienne à Morestel. Travail minutieux et propre. Rapport qualité-prix excellent.", date: "2026-02-01", source: "Google" },
    { name: "Thomas G.", rating: 4, text: "Installation d'un WC suspendu et remplacement de la robinetterie. Travail bien fait, juste un petit retard le jour du rendez-vous.", date: "2025-12-18", source: "Google" },
    { name: "Nathalie P.", rating: 5, text: "Très content de l'entretien de notre chaudière. Jimmy est ponctuel, sérieux et explique bien ce qu'il fait. On a signé un contrat d'entretien annuel.", date: "2026-01-30", source: "Google" },
    { name: "François H.", rating: 5, text: "Dépannage rapide et efficace pour une fuite dans notre salle de bain. Jimmy est un artisan de confiance, je le recommande à tous mes voisins de Bourgoin.", date: "2025-11-20", source: "Google" },
  ],
  admin: {
    password: "1234",
  },
  seo: {
    metaTitleAccueil: "Plombier Saint-Baudille-de-la-Tour — JD Maintenance et Plomberie | Dépannage 7j/7",
    metaDescAccueil: "Plombier chauffagiste à Saint-Baudille-de-la-Tour et Nord-Isère. Dépannage urgent 7j/7, installation, rénovation salle de bain, chauffage. Devis gratuit. 07 69 94 95 28.",
    descriptionEntreprise: "JD Maintenance et Plomberie, votre plombier chauffagiste à Saint-Baudille-de-la-Tour (38118). Dépannage urgent 7j/7, installation, rénovation salle de bain, chauffage. Devis gratuit.",
    slogan: "Votre plombier dans le Nord-Isère — Dépannage 7j/7, intervention rapide",
  },
} as const;

export type ClientConfig = typeof clientConfig;
